#!/usr/bin/env python3
"""Combine multiple per-pipeline CPI stack figures into a single grid.

Takes PNG images generated by pipeline_analysis.py and arranges them
in an NxM grid with optional labels.

Usage:
    # 2x2 grid with auto labels from filenames
    python scripts/combine_pipeline_figures.py \
        outputs/pipeline_minibude.png \
        outputs/pipeline_xsbench.png \
        outputs/pipeline_lulesh.png \
        outputs/pipeline_hipkittens.png \
        -o outputs/pipeline_combined.png

    # 2x2 grid with custom labels
    python scripts/combine_pipeline_figures.py \
        outputs/pipeline_minibude.png \
        outputs/pipeline_xsbench.png \
        outputs/pipeline_lulesh.png \
        outputs/pipeline_hipkittens.png \
        --labels "MiniBUDE" "XSBench" "LULESH" "HipKittens" \
        -o outputs/pipeline_combined.png

    # 1x3 single row
    python scripts/combine_pipeline_figures.py \
        a.png b.png c.png --cols 3 -o combined.png

    # Custom grid
    python scripts/combine_pipeline_figures.py \
        a.png b.png c.png d.png e.png f.png --cols 3 -o combined.png
"""

import argparse
import math
import re
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.image as mpimg


def label_from_filename(path: Path) -> str:
    """Extract a human-readable label from a pipeline figure filename.

    pipeline_minibude.png -> MiniBUDE
    pipeline_xsbench.png -> XSBench
    pipeline_hipkittens.png -> HipKittens
    """
    stem = path.stem
    # Strip common prefixes
    for prefix in ("pipeline_", "pipeline-"):
        if stem.startswith(prefix):
            stem = stem[len(prefix):]
    # Title-case but preserve known acronyms
    return stem.replace("_", " ").title()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Combine per-pipeline CPI stack figures into a grid",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "images", nargs="+", type=Path,
        help="Input PNG images (from pipeline_analysis.py)",
    )
    parser.add_argument(
        "-o", "--output", type=str, default="pipeline_combined.png",
        help="Output filename (default: pipeline_combined.png)",
    )
    parser.add_argument(
        "--cols", type=int, default=2,
        help="Number of columns in grid (default: 2)",
    )
    parser.add_argument(
        "--labels", nargs="+", type=str, default=None,
        help="Custom labels for each subplot (default: derived from filenames)",
    )
    parser.add_argument(
        "--no-labels", action="store_true",
        help="Suppress subplot labels entirely",
    )
    parser.add_argument(
        "--dpi", type=int, default=200,
        help="Output DPI (default: 200)",
    )
    args = parser.parse_args()

    n = len(args.images)
    cols = min(args.cols, n)
    rows = math.ceil(n / cols)

    # Resolve labels
    if args.no_labels:
        labels = [None] * n
    elif args.labels:
        if len(args.labels) != n:
            print(f"Error: {len(args.labels)} labels provided for {n} images", file=sys.stderr)
            return 1
        labels = args.labels
    else:
        labels = [label_from_filename(p) for p in args.images]

    # Read images
    imgs = []
    for p in args.images:
        if not p.exists():
            print(f"Error: {p} not found", file=sys.stderr)
            return 1
        imgs.append(mpimg.imread(str(p)))

    # Create figure
    fig, axes = plt.subplots(rows, cols, figsize=(8 * cols, 4 * rows))

    # Flatten axes for uniform indexing
    if rows == 1 and cols == 1:
        axes = [axes]
    elif rows == 1 or cols == 1:
        axes = list(axes)
    else:
        axes = [ax for row in axes for ax in row]

    for i, (img, label) in enumerate(zip(imgs, labels)):
        ax = axes[i]
        ax.imshow(img)
        ax.set_axis_off()
        if label:
            ax.set_title(label, fontsize=14, fontweight="bold", pad=8)

    # Hide unused cells
    for j in range(n, len(axes)):
        axes[j].set_axis_off()

    plt.tight_layout(pad=1.0)
    fig.savefig(args.output, dpi=args.dpi, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    print(f"Combined figure saved: {args.output} ({rows}x{cols} grid, {n} images)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
