#!/usr/bin/env python3
"""Generate paper-quality root-cause validation figure for SC26.

Reads pre-extracted data from results/validation/cache.json
(generated by extract_validation_data.py).

Usage:
    uv run python scripts/plot_validation_paper.py
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import json
import os

KERNELS_RAJA = [
    "MASS3DEA", "LT_NV", "LTIMES", "3MM", "2MM", "GEMM",
    "PRESSURE", "ENERGY", "FIR", "ZONAL_3D", "VOL3D", "DEL_DOT",
    "DIFF3DPA", "CONV3DPA", "MASS3DPA",
]
KERNELS_HPC = ["miniBUDE", "XSBench", "LULESH", "QuickSilv", "llama.cpp", "Kripke"]

KERNEL_DIR_MAP = {
    "MASS3DEA": "Apps_MASS3DEA", "LT_NV": "Apps_LTIMES_NOVIEW",
    "LTIMES": "Apps_LTIMES", "3MM": "Polybench_3MM", "2MM": "Polybench_2MM",
    "GEMM": "Polybench_GEMM", "PRESSURE": "Apps_PRESSURE", "ENERGY": "Apps_ENERGY",
    "FIR": "Apps_FIR", "ZONAL_3D": "Apps_ZONAL_ACCUMULATION_3D",
    "VOL3D": "Apps_VOL3D", "DEL_DOT": "Apps_DEL_DOT_VEC_2D",
    "DIFF3DPA": "Apps_DIFFUSION3DPA", "CONV3DPA": "Apps_CONVECTION3DPA",
    "MASS3DPA": "Apps_MASS3DPA",
    "miniBUDE": "miniBUDE", "XSBench": "XSBench", "LULESH": "LULESH",
    "QuickSilv": "quicksilver", "llama.cpp": "llamacpp", "Kripke": "kripke",
}

NVIDIA_GREEN = '#76B900'
AMD_RED = '#ED1C24'
INTEL_BLUE = '#0071C5'

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
LEO_ROOT = os.path.dirname(SCRIPT_DIR)
OUT_DIR = os.path.join(LEO_ROOT, "3rdparty/hpctoolkit_pcsampling/sc26/figures")
CACHE_PATH = os.path.join(LEO_ROOT, "results/validation/cache.json")


def plot_vendor(ax, kernels, data, color, title, show_ylabel=True):
    N = len(kernels)
    x = np.arange(N)
    width = 0.35
    VISUAL_FLOOR = 1.0

    befores, afters, has_data = [], [], []
    for b, a in data:
        if b is not None:
            befores.append(b)
            if b > 5.0 and a is not None and a < VISUAL_FLOOR:
                afters.append(VISUAL_FLOOR)
            else:
                afters.append(a if a is not None else 0)
            has_data.append(True)
        else:
            befores.append(0)
            afters.append(0)
            has_data.append(False)

    bars_b = ax.bar(x - width/2, befores, width, color=color, alpha=0.25,
                    edgecolor=color, linewidth=0.3, label='Before')
    bars_a = ax.bar(x + width/2, afters, width, color=color, alpha=0.85,
                    edgecolor=color, linewidth=0.3, label='After')

    for j in range(N):
        if not has_data[j]:
            bars_b[j].set_alpha(0)
            bars_a[j].set_alpha(0)

    ax.axhline(y=20, color='gray', linestyle='--', alpha=0.5, linewidth=0.5)
    ax.set_title(title, fontsize=6, fontweight='bold', pad=1)
    ax.set_xticks(x)
    ax.set_xticklabels(kernels, rotation=55, fontsize=3.5, ha='right')
    ax.set_ylim(0, 105)
    ax.tick_params(axis='y', labelsize=4.5, pad=0.5)
    ax.tick_params(axis='x', pad=0.5)
    if show_ylabel:
        ax.set_ylabel('Culprit Stall Burden (%)', fontsize=4.5, labelpad=1)


def main():
    with open(CACHE_PATH) as f:
        cache = json.load(f)

    all_kernels = KERNELS_RAJA + KERNELS_HPC

    def get_data(kernel_display, vendor):
        key = f"{KERNEL_DIR_MAP.get(kernel_display, kernel_display)}/{vendor}"
        d = cache.get(key)
        if not d:
            return (None, None)
        return (d["before_burden"], d["after_burden"])

    nv_data = [get_data(k, "nvidia") for k in all_kernels]
    amd_data = [get_data(k, "amd") for k in all_kernels]
    intel_data = [get_data(k, "intel") for k in all_kernels]

    # Print summary
    print("Validation Culprit Burden (%):")
    print(f"  {'Kernel':<12s} {'NVIDIA':>15s} {'AMD':>15s} {'Intel':>15s}")
    print("  " + "-" * 55)
    for i, k in enumerate(all_kernels):
        def fmt(d):
            b, a = d
            if b is None: return "N/A"
            if a is None: return f"{b:.1f}→?"
            return f"{b:.1f}→{a:.1f}%"
        print(f"  {k:<12s} {fmt(nv_data[i]):>15s} {fmt(amd_data[i]):>15s} {fmt(intel_data[i]):>15s}")

    for name, data in [("NVIDIA", nv_data), ("AMD", amd_data), ("Intel", intel_data)]:
        avail = sum(1 for b, a in data if b is not None and a is not None)
        dropped = sum(1 for b, a in data if b is not None and a is not None and b - a >= 10)
        print(f"  {name}: {avail} complete, {dropped} with ≥10pp drop")

    # ---- Figure 1: Burden (%) ----
    fig, axes = plt.subplots(1, 3, figsize=(7.2, 1.3), sharey=True)
    plot_vendor(axes[0], all_kernels, nv_data, NVIDIA_GREEN, 'NVIDIA H100', True)
    plot_vendor(axes[1], all_kernels, amd_data, AMD_RED, 'AMD MI300A', False)

    intel_kernels = KERNELS_RAJA + ["miniBUDE", "XSBench", "LULESH"]
    intel_plot = intel_data[:len(KERNELS_RAJA)] + intel_data[len(KERNELS_RAJA):len(KERNELS_RAJA)+3]
    plot_vendor(axes[2], intel_kernels, intel_plot, INTEL_BLUE, 'Intel PVC', False)

    axes[0].legend(fontsize=3.5, loc='upper right', framealpha=0.8,
                   handlelength=0.8, handletextpad=0.2, borderpad=0.2)

    plt.tight_layout(pad=0.1, w_pad=0.2)
    os.makedirs(OUT_DIR, exist_ok=True)
    pdf = os.path.join(OUT_DIR, 'validation_burden.pdf')
    fig.savefig(pdf, dpi=300, bbox_inches='tight')
    fig.savefig(pdf.replace('.pdf', '.png'), dpi=300, bbox_inches='tight')
    print(f"\nSaved burden figure to {pdf}")
    plt.close()

    # ---- Figure 2: Normalized absolute cycles (before=100%) ----
    def get_norm_data(kernel_display, vendor):
        """Return (100, after/before*100) for normalized cycle comparison."""
        key = f"{KERNEL_DIR_MAP.get(kernel_display, kernel_display)}/{vendor}"
        d = cache.get(key)
        if not d:
            return (None, None)
        bc = d["before_cycles"]
        ac = d["after_cycles"]
        if bc is None or bc == 0:
            return (None, None)
        if ac is None:
            return (100.0, None)
        return (100.0, ac / bc * 100.0)

    nv_norm = [get_norm_data(k, "nvidia") for k in all_kernels]
    amd_norm = [get_norm_data(k, "amd") for k in all_kernels]
    intel_norm = [get_norm_data(k, "intel") for k in all_kernels]

    # Print normalized summary
    print("\nNormalized Cycles (before=100%):")
    print(f"  {'Kernel':<12s} {'NVIDIA':>12s} {'AMD':>12s} {'Intel':>12s}")
    print("  " + "-" * 45)
    for i, k in enumerate(all_kernels):
        def fmt_n(d):
            b, a = d
            if b is None: return "N/A"
            if a is None: return "100→?"
            return f"100→{a:.0f}%"
        print(f"  {k:<12s} {fmt_n(nv_norm[i]):>12s} {fmt_n(amd_norm[i]):>12s} {fmt_n(intel_norm[i]):>12s}")

    for name, data in [("NVIDIA", nv_norm), ("AMD", amd_norm), ("Intel", intel_norm)]:
        avail = sum(1 for b, a in data if b is not None and a is not None)
        reduced = sum(1 for b, a in data if b is not None and a is not None and a < 50)
        print(f"  {name}: {avail} complete, {reduced} with ≥50% cycle reduction")

    def plot_vendor_norm(ax, kernels, data, color, title, show_ylabel=True):
        N = len(kernels)
        x = np.arange(N)
        width = 0.35
        VISUAL_FLOOR = 2.0

        befores, afters, has_data = [], [], []
        for b, a in data:
            if b is not None:
                befores.append(b)
                if a is not None and a < VISUAL_FLOOR:
                    afters.append(VISUAL_FLOOR)
                else:
                    afters.append(a if a is not None else 0)
                has_data.append(True)
            else:
                befores.append(0)
                afters.append(0)
                has_data.append(False)

        bars_b = ax.bar(x - width/2, befores, width, color=color, alpha=0.25,
                        edgecolor=color, linewidth=0.3, label='Before')
        bars_a = ax.bar(x + width/2, afters, width, color=color, alpha=0.85,
                        edgecolor=color, linewidth=0.3, label='After')

        for j in range(N):
            if not has_data[j]:
                bars_b[j].set_alpha(0)
                bars_a[j].set_alpha(0)

        ax.axhline(y=50, color='gray', linestyle='--', alpha=0.5, linewidth=0.5)
        ax.set_title(title, fontsize=6, fontweight='bold', pad=1)
        ax.set_xticks(x)
        ax.set_xticklabels(kernels, rotation=55, fontsize=3.5, ha='right')
        ax.set_ylim(0, 120)
        ax.tick_params(axis='y', labelsize=4.5, pad=0.5)
        ax.tick_params(axis='x', pad=0.5)
        if show_ylabel:
            ax.set_ylabel('Culprit Stall Cycles\n(normalized, before=100%)', fontsize=4.5, labelpad=1)

    fig2, axes2 = plt.subplots(1, 3, figsize=(7.2, 1.3), sharey=True)
    plot_vendor_norm(axes2[0], all_kernels, nv_norm, NVIDIA_GREEN, 'NVIDIA H100', True)
    plot_vendor_norm(axes2[1], all_kernels, amd_norm, AMD_RED, 'AMD MI300A', False)

    intel_norm_plot = intel_norm[:len(KERNELS_RAJA)] + intel_norm[len(KERNELS_RAJA):len(KERNELS_RAJA)+3]
    plot_vendor_norm(axes2[2], intel_kernels, intel_norm_plot, INTEL_BLUE, 'Intel PVC', False)

    axes2[0].legend(fontsize=3.5, loc='upper right', framealpha=0.8,
                    handlelength=0.8, handletextpad=0.2, borderpad=0.2)

    plt.tight_layout(pad=0.1, w_pad=0.2)
    pdf2 = os.path.join(OUT_DIR, 'validation_cycles.pdf')
    fig2.savefig(pdf2, dpi=300, bbox_inches='tight')
    fig2.savefig(pdf2.replace('.pdf', '.png'), dpi=300, bbox_inches='tight')
    print(f"Saved cycles figure to {pdf2}")
    plt.close()


if __name__ == '__main__':
    main()
